// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type Job struct {
	DockerImage string  `json:"docker_image"`
	Dataset     *string `json:"dataset"`
}

type Task struct {
	ID        string    `json:"id"`
	CreatedBy string    `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	StartedAt time.Time `json:"started_at"`
	EndedAt   time.Time `json:"ended_at"`
	Status    Status    `json:"status"`
	Job       *Job      `json:"job"`
}

type User struct {
	ID        string    `json:"id"`
	Admin     bool      `json:"admin"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type NewTask struct {
	UserID      string  `json:"user_id"`
	DockerImage string  `json:"docker_image"`
	Dataset     *string `json:"dataset"`
}

type NewUser struct {
	Email string `json:"email"`
}

type Status string

const (
	StatusStatusless Status = "STATUSLESS"
	StatusFailed     Status = "FAILED"
	StatusNotStarted Status = "NOT_STARTED"
	StatusRunning    Status = "RUNNING"
	StatusEnded      Status = "ENDED"
	StatusCanceled   Status = "CANCELED"
)

var AllStatus = []Status{
	StatusStatusless,
	StatusFailed,
	StatusNotStarted,
	StatusRunning,
	StatusEnded,
	StatusCanceled,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusStatusless, StatusFailed, StatusNotStarted, StatusRunning, StatusEnded, StatusCanceled:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
