// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Task struct {
	ID        string     `json:"id"`
	CreatedBy *User      `json:"created_by"`
	CreatedAt time.Time  `json:"created_at"`
	StartedAt *time.Time `json:"started_at"`
	EndedAt   *time.Time `json:"ended_at"`
	Failed    *bool      `json:"failed"`
	Job       int        `json:"job"`
}

type User struct {
	ID    string `json:"id"`
	Login string `json:"login"`
	Email string `json:"email"`
}

type NewTask struct {
	UserID int `json:"user_id"`
	Job    int `json:"job"`
}

type NewUser struct {
	Login string `json:"login"`
	Email string `json:"email"`
}
