// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Job struct {
	ID          string  `json:"id"`
	CreatedBy   *User   `json:"created_by"`
	DockerImage string  `json:"docker_image"`
	Dataset     *string `json:"dataset"`
}

type Task struct {
	ID        string    `json:"id"`
	CreatedBy *User     `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	StartedAt time.Time `json:"started_at"`
	EndedAt   time.Time `json:"ended_at"`
	Failed    bool      `json:"failed"`
	Job       *Job      `json:"job"`
}

type User struct {
	ID        string    `json:"id"`
	Admin     bool      `json:"admin"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type NewTask struct {
	UserID      string  `json:"user_id"`
	DockerImage string  `json:"docker_image"`
	Dataset     *string `json:"dataset"`
}

type NewUser struct {
	Email string `json:"email"`
}
